# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'testmaps' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testmaps
  pod 'React',
      :path => "../node_modules/react-native",
      :subspecs => [
        "Core",
        "ART",
        "RCTActionSheet",
        "RCTAnimation",
        "RCTCameraRoll",
        "RCTGeolocation",
        "RCTImage",
        "RCTNetwork",
        "RCTText",
        "RCTVibration",
        "RCTWebSocket",
        "DevSupport",
        "BatchedBridge"
      ]
  pod 'Yoga', :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'GoogleMaps'
  pod 'react-native-maps', path: '../node_modules/react-native-maps/'
  pod 'react-native-google-maps', path: '../node_modules/react-native-maps/'

  target 'testmapsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "react-native-google-maps"
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
    end
end

target 'testmaps-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testmaps-tvOS

  target 'testmaps-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
